media:
  input: public/media
  output: /media
content:
  - name: wiki
    label: Wiki Pages
    type: collection
    path: src/content/wiki
    fields:
      - name: hidden
        label: Should Hide
        type: boolean
        default: false
      - name: title
        label: Title
      - name: goto
        label: GoTo URL
        required: false
        pattern: {message: "Must be a valid URL", regex: "^https?:\/\/[^\s/$.?#].[^\s]*$" }
  - name: testimonials
    label: Testimonials
    type: collection
    path: src/content/testimonials
    view:
      fields: ["author", "org.name", "hidden"]
    fields:
      - name: hidden
        label: Should Hide
        type: boolean
        default: false
      - name: author
        label: Author Name
      - name: org
        label: Organization
        fields:
          - name: name
            label: Name
          - name: title
            label: Title / Position
          - name: url
            label: URL
            pattern: {message: "Must be a valid URL", regex: "^https?:\/\/[^\s/$.?#].[^\s]*$" }
      - name: body
        label: Body
        type: rich-text